spring.application.name=jellycat
spring.datasource.url=jdbc:postgresql://localhost:5000/cloud_chat
spring.datasource.username=chat_user
spring.datasource.password=chat_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
